### ISSUE TITLE
I don't see any usage for the durable storage APIs, is this by design?

### ISSUE THREAD

**Issue by faisalil** [cloudflare/dog#11]
in the examples or the logic for the library, I don't see any usage for the durable storage APIs. is this by design? what would happen if the durable objects got evicted? everything will fail, right?

**Comment by lukeed** [comment]
The DOG runtime is holding a record of active connections in memory. If the DOs crash then the connections drop & there's no reason for the previous record(s) to exist/restore since they're no longer applicable anyway. So the TLDR is that storage APIs aren't used for DOG internals because the internals don't make sense for persistence. 

However, storage is still accessible by your custom classes so that you may store whatever long-lived information that makes sense for your own needs.

**Comment by faisalil** [comment]
@lukeed thanks, makes sense. What is the best way you see to hold storage that exist at the Group level? lets say you want to store the chat history in the lobby (for the example), any suggestion on how to do that?

**Comment by lukeed** [comment]
The follow-up question has been moved to #12 & will close this in favor of that ticket. Thanks~!
