### ISSUE TITLE
Why "let"?

### ISSUE THREAD

**Issue by mikecann** [cloudflare/dog#5]
Im wondering why you use "let" all over the ts codebase when `const` is generally preferred?

**Comment by lukeed** [comment]
I really doesn't matter much. I plan to eventually come back through and update these while I implement #2, The short answer is that it comes down to code style

**Comment by mikecann** [comment]
Well `const` allows for literal types in TS and obviously prevents accidental mutability.

**Comment by lukeed** [comment]
Yep! No argument here. Just didn't need or want either while developing this. For me I generally come back through and "lock in" please declaration hints once everything isn't really in transit anymore (since let-vs-const is really about knowledge share & long-term maintenance and let->const can be automated)
