### ISSUE TITLE
Relaying external data to connected WebSocket clients across Replicas

### ISSUE THREAD

**Issue by scottgarner** [cloudflare/dog#7]
I'm looking for a way to effectively relay incoming POST data associated with a given ID to all connected WS clients watching for the same ID, across all replicas. 

There doesn't seem to be a straightforward way to `broadcast/emit/whisper/send` without being a WS connection already. My initial approach was to manage a set of WS connections through their respective `onopen/onclose` calls. I then use that set to lookup recipients when POST data came in. That "works" until you have incoming POST data and multiple WS clients spread across replicas.

The best I can come up with at the moment is to keep managing my own connection set, then when POST data comes in, send it to any connected clients that happen to be on the same replica, then `gossip` the data to all other replicas so they can send as needed, too. This feels convoluted, but maybe it's the best way?

**Comment by lukeed** [comment]
This is the best way currently. As you said, this is because you're crossing protocols and since you're starting in HTTP you don't have access to any of the socket convenience methods.

To recap, add a data structure within your Replica that holds onto Socket instances & facilitates your filtering needs. I'd add a method that handles this ID -> filter -> send sequence, using emit since it's Replica-contained. Then when a POST comes in, the receiver Replica calls that method & sends out a gossip to other peers who do the same thing (since they also have the same method defined).

Maybe can look at adding a core method to help orchestrate this HTTP -> WS broadcast

**Comment by scottgarner** [comment]
Thanks for the response! I was able to get this working, though I had to use `send` on individual sockets instead of using `emit` because I only wanted to talk to a subset of all clients on a given replica.

Easier methods to do HTTP -> WS would be great. The ability to send/gossip to all replicas directly from the group would also be really helpful.
