### ISSUE TITLE
Fetch API cannot load: /~$~/identify

### ISSUE THREAD

**Issue by scottgarner** [cloudflare/dog#8]
I have a working implementation using DOG that runs without issue locally in miniflare. When deployed, I get the following exception:

```
"Fetch API cannot load: /~$~/identify",
```

This is, I think, the related block of code.

```
      const group = env.CHANNEL_GROUP.idFromName('gateway');
      const replica = await identify(group, channelId, {
          parent: env.CHANNEL_GROUP,
          child: env.CHANNEL_REPLICA
        });
```

I see that `/~$~/identify` is used internally for routing, but I can't figure out what is causing the problem. To make matters more confusing, I'm almost certain I had at least a few deploys work without issue while going back and forth during testing.

**Comment by lukeed** [comment]
Ah, I should come back and update this.

Since dog was created, Durable Objects added a change (before GA) that required fetch() to receive fully qualified URLs...so the `/~$~/...` routing I have for internal communication isn't going to work.

You can disable this behavior & go back to the original DO behavior by adding this disable-flag to your wrangler config: https://developers.cloudflare.com/workers/platform/compatibility-dates#durable-object-stubfetch-requires-a-full-url

**Comment by scottgarner** [comment]
That did the job. Thanks! For anyone else with the issue, my entry in `wrangler.toml` looks like this:

```
compatibility_date = "2021-12-01"
compatibility_flags = [ "durable_object_fetch_allows_relative_url" ]
```
